# Generated by Django 6.1 on 2026-09-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('rating', models.FloatField()),
                ('poster_path', models.CharField(max_length=200)),
                ('backdrop_path', models.CharField(max_length=200)),
                ('genres', models.JSONField()),
                ('runtime', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('realease_date', models.DateTimeField()),
                ('season_number', models.IntegerField()),
                ('episode_number', models.IntegerField()),
                ('episode_name', models.CharField(max_length=100)),
                ('episode_description', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('country', models.CharField(max_length=10)),
            ],
        ),
    ]
